name: Update Scholar Feed

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install requests

      - name: Run script
        env:
          SERPAPI_KEY: ${{ secrets.SERPAPI_KEY }}
        run: |
          python RSS.py

      - name: Commit updates
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add scholar_complete.json

          git diff --staged --quiet || git commit -m "Update Scholar Data"

          git push
